version: '2.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: '-Xms256m -Xmx256m'
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      discovery.type: single-node

    networks:
      app-network:
        ipv4_address: 172.22.0.10

  server:
    build:
      context: './server'
      dockerfile: Dockerfile
    container_name: node-server
    ports:
      - '8080:8080'
    volumes:
      - ./server:/src/app
    environment:
      - PORT=8080
      - NODE_ENV=development

    networks:
      app-network:
        ipv4_address: 172.22.0.12
    depends_on:
      - elasticsearch

  proxy:
    image: dperson/torproxy
    container_name: proxy
    ports:
      - '9050:9050'
      - '8118:8118'
    networks:
      app-network:
        ipv4_address: 172.22.0.13

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
